name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        gcc-version: [10]
          
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Update GCC
      id: update-gcc
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.gcc-version }}

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: 1.59

    - name: Create default profile
      run: | 
        conan profile new default --detect
        conan profile update settings.build_type=${{ matrix.build-type }} default
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Configure CMake Debug
      if: ${{ matrix.build-type == 'Debug' }}
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug -DUSE_CLANG_TIDY=ON -DCODE_COVERAGE=ON

    - name: Configure CMake Release
      if: ${{ matrix.build-type == 'Release' }}
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DUSE_CLANG_TIDY=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }} -j 3

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-type }} --output-on-failure

    - name: Prepare Codecov
      if: ${{ matrix.build-type == 'Debug' }}
      run: |
        sudo apt-get install -y lcov
        lcov --directory . --capture --output-file coverage.info --rc lcov_branch_coverage=1 # capture coverage info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info --rc lcov_branch_coverage=1 # filter out system
        lcov --remove coverage.info '/home/runner/.conan/*' --output-file coverage.info --rc lcov_branch_coverage=1 # filter out conan files
        lcov --list coverage.info --rc lcov_branch_coverage=1 # debug info

    - name: Codecov
      if: ${{ matrix.build-type == 'Debug' }}
      uses: codecov/codecov-action@v3.1.1
      with:
        files: coverage.info
        fail_ci_if_error: true
        verbose: true

  macos-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
          
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Select Python 3.10
      # otherwise turtlebrowser/get-conan@v1.1 fails on macos-12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: 1.59

    - name: Create default profile
      # M1 is not supported by all dependencies
      run: | 
        conan profile new default --detect
        conan profile update settings.build_type=${{ matrix.build-type }} default
        conan profile update settings.arch=x86_64 default
        conan profile update settings.arch_build=x86_64 default

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }} -j 3

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-type }} --output-on-failure

  windows-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        msvc-version: [16]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: 1.59

    - name: Create default profile
      run: | 
        conan profile new default --detect
        conan profile update settings.build_type=${{ matrix.build-type }} default
        conan profile update settings.compiler.version=${{ matrix.msvc-version }} default

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CONFIGURATION_TYPES=${{ matrix.build-type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }} -j 3

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-type }} --output-on-failure
