name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Get GCC-10
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 10
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    
    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Update profile compiler
      run: conan profile update settings.compiler=gcc default
      
    - name: Update profile compiler version
      run: conan profile update settings.compiler.version=10 default

    - name: Update profile libstd
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    
    - name: Install Dependencies
      run: conan install . -if ${{github.workspace}}/build -s build_type=${{matrix.build-type}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}} -j 3

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}} --output-on-failure
      
