name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest]
        compiler: [{cpp: g++, c: gcc, version: 10}, {cpp: g++, c: gcc, version: 12}, {cpp: clang++, c: clang, version: 13}, {cpp: clang++, c: clang, version: 15}]
        exclude:
          - os: macos-latest
            compiler: {cpp: g++}

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - if: matrix.compiler.c == 'gcc':
      name: Get GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{matrix.compiler.version}}
    
    - if: matrix.compiler.c == 'clang':
      name: Get Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{matrix.compiler.version}}
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    
    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Update profile compiler
      run: conan profile update settings.compiler=${{matrix.compiler.c}} default
      
    - name: Update profile compiler version
      run: conan profile update settings.compiler.version=${{matrix.compiler.version}} default

    - name: Update profile libstd
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    
    - name: Install Dependencies
      run: conan install . -if ${{github.workspace}}/build -s build_type=${{matrix.build-type}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
      env:
        CC:   ${{matrix.compiler.c}}-${{matrix.compiler.version}}
        CXX:  ${{matrix.compiler.cpp}}-${{matrix.compiler.version}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}} -j 3

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}} --output-on-failure
      
