name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - name: Get GCC-10
      run: sudo apt install g++-10
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    
    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Update profile compiler
      run: conan profile update settings.compiler=gcc default
      
    - name: Update profile compiler version
      run: conan profile update settings.compiler.version=10 default

    - name: Update profile libstd
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    
    - name: Install Dependencies
      run: conan install . -if ${{github.workspace}}/build -s build_type=${{env.BUILD_TYPE}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
